# Generated by Django 6.0.5 on 2026-05-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lider', models.CharField(max_length=100)),
                ('dia_reuniao', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Célula',
                'verbose_name_plural': 'Células',
                'ordering': ['nome'],
            },
        ),
    ]
