# Generated by Django 6.0.5 on 2026-05-29 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_batismo', models.DateField(blank=True, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('ministerio', models.CharField(choices=[('louvor', 'Louvor'), ('ensino', 'Ensino'), ('intercessao', 'Intercessão'), ('diaconia', 'Diaconia'), ('evangelismo', 'Evangelismo'), ('infantil', 'Infantil'), ('nenhum', 'Nenhum')], default='nenhum', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('visitante', 'Visitante')], default='ativo', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='membros/fotos/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('celula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='groups.group')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome'],
            },
        ),
    ]
